### PR TITLE
Fix thumbnail orientation for silly browsers

### PR DESCRIPTION
**Pull request by clbn**
It rotates image according to EXIF "orientation" property and then strips EXIF profile.

### CODE REVIEW

**Comment by epicmonkey** [comment]
Does it really strip EXIF as description said?

**Comment by clbn** [comment]
Yes. You can compare EXIF by yourself: http://frf.creagenics.com:3333/clbn3/08115376-f478-4509-9e93-7d2fca526623

GraphicsMagick didn't have `-auto-orient` until v1.3.18 (March 10, 2013). Now there is such option, but it's really [half-assed](http://www.graphicsmagick.org/NEWS.html#march-10-2013): 

> convert/mogrify: Now support -auto-orient to automatically rotate the image upright for viewing based on its current orientation setting. Also support -orient to support setting the current image orientation. Please note that the orientation property of EXIF profiles is not yet updated so the EXIF profile will be wrong after using -auto-orient.

Fortunately, in `gm` node package the implementation mimics ImageMagick's `-auto-orient`, and that's what I found in their code: https://github.com/aheckmann/gm/pull/21/files#diff-43bc23029a025a10c970aada87f9dc65R36

Hence the comment on stripping EXIF.

**Comment by clbn** [comment]
Actually, current version if different, but it still strips EXIF: https://github.com/aheckmann/gm/blob/357c81706638b2ce7c1a3a21a4ec0dd92212557b/lib/convenience/autoOrient.js

**Comment by epicmonkey** [comment]
Nice to know. Thanks.

**Comment by clbn** [comment]
Actually, this fixes #199.

**Pull request merged**
